### ISSUE TITLE
Original patch_mp.ff

### ISSUE THREAD

**Issue by michaeloliverx** [ClementDreptin/mos#1]
Thanks for this repo, it's nice to see this on GitHub instead of random downlinks on forums.

I am currently doing research on call of duty modifications as a hobby project. I already have a patched `default_mp.xex` and a `patch_mp.ff`, my question is where did this file initially come from? How would I generate an untouched version?

Also do you have any information on how the `default_mp.xex` was patched initially? I'd love to learn more about the technical side of this.

**Comment by ClementDreptin** [comment]
FastFiles (.ff) are sort of "zip archives" that contain game scripts and assets. You can't simply take the official `patch_mp.ff` file that comes with title updates and edit it because its size is determined at link time (when the scripts and assets are put together). This means you could theoretically replace some existing content with yours but that would break the game.

To overcome this limitation, people have exported the data contained in the official `patch_mp.ff` file, added some empty scripts but allocated a lot of space for them, and linked the FastFile again. This way you have empty scripts with sufficient allocated space for you to insert your code.

What tools were used and who created this file remain unclear. These days, there are plenty of open source solutions that didn't exist back when this file was first created. [ZoneTool](https://github.com/ZoneTool/zonetool) is a FastFile linker that can put together GSC scripts and assets into FastFiles. Up until what I believe is IW5 (so MW3), FastFiles contained GSC scripts, so source code as text. Now they contain GSC bytecode, which is created by an internal GSC compiler at Activision. Fortunately for us, we have [gsc-tool](https://github.com/xensik/gsc-tool) which is a fantastic GSC compiler that can be used to compile scripts to GSC bytecode.
I've never created a FastFile myself but I know it's a little bit more involved than what I just described.

I don't exactly know how the patched `default_mp.xex` file was first created. All I know is that it is required to load the modified version of `patch_mp.ff`. It was probably created by modifying some instructions and/or data in the file directly using an interactive disassembler such as [IDA](https://hex-rays.com/ida-pro/).

I'm by no means an expert on the subject, I'm just sharing what I learned over the years.

Hope it helps!

**Comment by michaeloliverx** [comment]
Thank you so much for the information!, it helped me discover that the title update files contain the `patch_mp.ff` and `default_mp.xex`. I am working with Call of Duty 4 Modern Warfare specifically so I was able to extract an original `patch_mp.ff` from the title update 4 file using [x360 Tool](https://www.360-hq.com/xbox360-homebrew-19-x360_Tool.html). This gives me a good base to start writing some GSC scripts.

BTW really cool repositories you have here for xbox 360 hacking information!

**Comment by ClementDreptin** [comment]
Thank you very much!

I put a lot of effort into making them good resources for people to learn, because I learned most of what I know by looking at other people's code.

**Comment by michaeloliverx** [comment]
Hey just another random question, the R2R menu you mention is mo's, that wouldn't happen to be mo teh pro would it? 😄

**Comment by ClementDreptin** [comment]
Yes it is, it is generally called like that because the very first version was written by him. The original code was very messy though so the code from this project is essentially a rewrite, I don't think there's anything left from the original code.

**Comment by michaeloliverx** [comment]
> Yes it is, it is generally called like that because the very first version was written by him. The original code was very messy though so the code from this project is essentially a rewrite, I don't think there's anything left from the original code.

When I first commented on this issue I didn't actually notice you had mentioned mo. This is hilarious because I am actually mo teh pro 🤣 mo is my initials/nickname.

I was very young back then and didn't really know what I was doing, but I'm a Software Engineer now haha. I made the original release [here](https://www.se7ensins.com/forums/threads/release-my-glitching-menu.766942/)

I've recently returned to Cod4 and was creating a fresh CodJumper patch. I am trying to learn GSC stuff.

I've managed to do:
- save/load position
- unlimited ammo (with reload animation)
- spawn bots at player origin to be used for blockers / slide bounces etc
- remove RPG smoke
- UFO Mode

I don't have an actual menu though so all the actions were simply binded to buttons directly. I've been looking for menu examples using shaders etc and came across this repo again!


Your code looks nice and clean and I'll certainly try it out! I may open a PR or two!


---

Btw if you are interested in CodJumping I recently started a discord and gathered a bunch of CodJumpers from the past to join. We plan to make at least a few videos with new bounces/jumps. You are welcome to join!

https://discord.gg/Kx5B5UfE
